### ISSUE TITLE
SimGetImages：msgpackrpc.error.RPCError

### ISSUE THREAD

**Issue by June-Smith** [CodexLabsLLC/Colosseum#109]
## Bug report 

- AirSim Version/#commit:I have tried every version of colosseum
- UE/Unity version:5.1 5.2 5.3 5.4 
- autopilot version:
- OS Version:windows 10

### What's the issue you encountered?

The error code is the following sentence：
responses = client.simGetImages(
ImageRequest('0', ImageType.Scene, False, False)
)

### Settings

default setting

### How can the issue be reproduced?

I didn't change anything, just follow the tutorial configuration and use the python api to get the image.

### Include full error message in text form
Traceback (most recent call last):
File "C:\Users\test\PycharmProjects\airsim_test\test2.py", line 13, in
responses = client.simGetImages(
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\test.conda\envs\airsim\Lib\site-packages\airsim\client.py", line 309, in simGetImages
responses_raw = self.client.call('simGetImages', requests, vehicle_name, external)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\test.conda\envs\airsim\Lib\site-packages\msgpackrpc\session.py", line 41, in call
return self.send_request(method, args).get()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\test.conda\envs\airsim\Lib\site-packages\msgpackrpc\future.py", line 45, in get
raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: function 'simGetImages' (called with 3 arg(s)) threw an exception. The exception contained this information: bad cast.

**What's better than filing an issue? Filing a pull request :).**

**Comment by taeseongkr** [comment]
same issue. Did you solve it @YijingGuo-June ?

**Comment by 7REVOLUTiOn** [comment]
> same issue. Did you solve it @YijingGuo-June ?

Hi, maybe you could find a solution?

**Comment by taeseongkr** [comment]
@7REVOLUTiOn @YijingGuo-June Thank you. I solved the issue. Appreciate your help!

**Comment by 7REVOLUTiOn** [comment]
> @7REVOLUTiOn @YijingGuo-JuneСпасибо. Я решил проблему. Ценю вашу помощь!

If it's not a secret, how did you solve it? This problem is quite common.

**Comment by Duckierstone42** [comment]
I believe I found a solution that works. I get the same issue as you if i install airsim from pip, but I think the airsim from pip is severely out of date. What you need to do instead is go into the PythonClient folder in colosseum and do "pip install ." to install it from source.

**Comment by 7REVOLUTiOn** [comment]
> I believe I found a solution that works. I get the same issue as you if i install airsim from pip, but I think the airsim from pip is severely out of date. What you need to do instead is go into the PythonClient folder in colosseum and do "pip install ." to install it from source

Thanks, it's working. Indeed, I used the airsim library from pip. I think the documentation for Collezium is very outdated and needs to be updated at some points. Thanks again

**Comment by Hangero** [comment]
> > I believe I found a solution that works. I get the same issue as you if i install airsim from pip, but I think the airsim from pip is severely out of date. What you need to do instead is go into the PythonClient folder in colosseum and do "pip install ." to install it from source我相信我找到了一个可行的解决方案。如果我从 pip 安装 airsim，也会遇到和你一样的问题，但我认为 pip 中的 airsim 版本严重过时了。你需要做的是进入 colosseum 中的 PythonClient 文件夹，然后运行“pip install .”从源代码安装它。
> 
> Thanks, it's working. Indeed, I used the airsim library from pip. I think the documentation for Collezium is very outdated and needs to be updated at some points. Thanks again谢谢，它已经正常工作了。我确实用了 pip 的 airsim 库。我觉得 Collezium 的文档太旧了，需要在某些地方更新。再次感谢

You can directly use `pip install airsim==1.8.1`. This issue is due to an outdated version of AirSim.
