### ISSUE TITLE
Unreal engine 5

### ISSUE THREAD

**Issue by Davidsastresas** [CodexLabsLLC/Colosseum#18]
I tried to build your branch for ue 5, but I wasn't able to, I had several errors. In case the porting is not finished, I would love to help in the porting. Thanks!

**Comment by xxEoD2242** [comment]
Hey @Davidsastresas,

What errors did you have?

**Comment by xxEoD2242** [comment]
When you switched branches, did you do `clean_rebuild.bat`?

**Comment by Davidsastresas** [comment]
I did separately a clean.cmd and a build.cmd. I tried to do now the clean_rebuild.bat, and apparently I get the same result.

I wonder if my unreal engine version is the issue here. It seems the build process completes almost successfully, and it complains when generating the uproject files, when this popup appears. Before it, it asks you to confirm the unreal engine version, and in my case I am using the latest 5.1. I wonder if you guys did this for 5.0 and something is different. I will try on 5.0 and report back.

Thanks!

**Comment by Davidsastresas** [comment]
Okey, it seems it builds correctly. I think it does all the build.cmd all right until update_from_git.bat. I think the issue comes only from generating the uproject files for airsim environment. I am trying to debug this now, will report back If I find something. Thanks!

**Comment by Davidsastresas** [comment]
Okey, I think I isolated the issue. Build.cmd runs fine up to update_from_git.bat. When it calls GenerateProjectFiles.bat it fails. This should affect only Blocks Environment but I assume it will affect other environments as well if I build more, so I would like to fix it.

The complete error appearing in the popup when GenerateProjectFiles.bat is as follows:

Running C:/Program Files/Epic Games/UE_5.1/Engine/Build/BatchFiles/Build.bat  -projectfiles -project="G:/AirsimColosseum/Unreal/Environments/Blocks/Blocks.uproject" -game -rocket -progress -log="G:\AirsimColosseum\Unreal\Environments\Blocks/Saved/Logs/UnrealVersionSelector-2022.12.07-14.07.19.log"
Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" -projectfiles -project="G:/AirsimColosseum/Unreal/Environments/Blocks/Blocks.uproject" -game -rocket -progress -log="G:\AirsimColosseum\Unreal\Environments\Blocks/Saved/Logs/UnrealVersionSelector-2022.12.07-14.07.19.log"
Log file: G:\AirsimColosseum\Unreal\Environments\Blocks\Saved\Logs\UnrealVersionSelector-2022.12.07-14.07.19.log
Log file: C:\Users\david\AppData\Local\UnrealBuildTool\Log_GPF.txt

Some Platforms were skipped due to invalid SDK setup: IOS, Android, Linux, LinuxArm64.
See the log file for detailed information

Discovering modules, targets and source code for project...
Binding IntelliSense data...
Library 'Shell32.lib' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning. 
Library 'dinput8.lib' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning. 
Library 'dxguid.lib' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning. 
Exception while generating include data for BlocksEditor: Could not find definition for module 'APEX', (referenced via Target -> AirSim.Build.cs)
Binding IntelliSense data... 100%
Writing project files...
Writing project files... 67%
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at UnrealBuildTool.VSCodeProjectFileGenerator.WriteConfiguration(String Name, String ProjectName, IEnumerable`1 SourceFiles, CppStandardVersion CppStandard, FileReference CompilerPath, DirectoryReference SysRootPath, Dictionary`2 ModuleCommandLines, JsonFile OutFile, DirectoryReference OutputDirectory) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudioCode\VSCodeProjectFileGenerator.cs:line 670
   at UnrealBuildTool.VSCodeProjectFileGenerator.WriteCppPropertiesFile(DirectoryReference OutputDirectory, ProjectData Projects) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudioCode\VSCodeProjectFileGenerator.cs:line 656
   at UnrealBuildTool.VSCodeProjectFileGenerator.WritePrimaryProjectFile(ProjectFile UBTProject, PlatformProjectGeneratorCollection PlatformProjectGenerators, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudioCode\VSCodeProjectFileGenerator.cs:line 281
   at UnrealBuildTool.ProjectFileGenerator.WriteProjectFiles(PlatformProjectGeneratorCollection PlatformProjectGenerators, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\ProjectFileGenerator.cs:line 2821
   at UnrealBuildTool.ProjectFileGenerator.GenerateProjectFiles(PlatformProjectGeneratorCollection PlatformProjectGenerators, String[] Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\ProjectFileGenerator.cs:line 1176
   at UnrealBuildTool.GenerateProjectFilesMode.Execute(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\GenerateProjectFilesMode.cs:line 233
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 648

**Comment by xxEoD2242** [comment]
What version of UE? 5.0 or 5.1

The current branch does not work with 5.1

**Comment by Davidsastresas** [comment]
I was trying on 5.1. Thanks for clarifying. 

I will download the 5.0 engine and try again. Just out of curiosity, do you also prefer windows for Unreal related stuff? For some reason when I tried myself in linux the editor just consumed way more resources, and it took more time for everything than working in windows.

Thanks!

**Comment by xxEoD2242** [comment]
Hey @Davidsastresas, did reverting back to 5.0.3 help?

Also, I definitely prefer any of the environment building on Windows but like to do all of my robotics development on Linux. So, I usually build binaries in Linux for all of my environments and work that way

**Comment by Davidsastresas** [comment]
Hello, I spared some time today and I got it working in 5.0.3, thank you very much. I only tested the Blocks project though, I haven't ported the plugin to a different uproject yet, but I expect it would go fine if Blocks works. Although there is still some stuff I would like to fix:

- Random warnings related to deprecated code, although it seems to build fine. I guess we need to port those parts to whatever it is the new way of doing it.

- When running build.bat, the part about downloading high-poly car assets fails, my understanding is that it tries to download something but doesn't find it. I checked some of your latest commits are related to this, although I haven't really looked into them. Not really important for me as I am only interested in multirotor, but I would love to help to fix it.

- I am having trouble packaging for Linux from Windows. I manually downloaded the proper toolchain recommended for this unreal version, and it is recognized by Unreal and everything, but when building it gets some errors. 

My understanding is that somehow I would need to do the equivalent of "build.bat" for linux, I think that is why packaging isn't working. Do you have any information about this? I was about to try to do this in WSL, but If you have any suggestion here it would be really welcomed.

- After building Airsim, and opening the unreal project, it always complains that the plugin ( Airsim ) was built with a different version of the engine. My feeling is that something in the build.cmd is using an older than 5.0 toolchain for unreal. It was converted on place but it is annoying that it could happen every time we add Airsim to an unreal project.

Let me know if the above makes sense to you, and if you want me to raise separate issues for them. I plan to work on Airsim for the following weeks so hopefully I will be able to contribute to some of it if needed.

Thank you very much for your clarification about your workflow. That was my feeling as well, thank you for confirming. I also prefer Linux for anything related to development so I will follow the same workflow.

If I may ask, what is your usual workflow for developing over Airsim? The official docs explain that workflow of using the update_from_git.bat, etc etc, using visual studio and everything, but I am sure there is a "faster" development workflow. I have curently integrated vscode instead of visual studio on Unreal, and I will try to think of something to make this process quicker. If you have any suggestion here It would be really welcomed.

Thank you very much!
