### ISSUE TITLE
Unable to properly run dqn_drone.py

### ISSUE THREAD

**Issue by shashwatkansal** [CodexLabsLLC/Colosseum#50]
## Bug report 

- AirSim Version/#commit: 052228ae6c9a03ba5ccd2ffd6422f1433588302b
- UE/Unity version: 5.1.1
- autopilot version:
- OS Version: Windows11 Version 22H2, OS Build 22621.1702

### What's the issue you encountered?

I have built AirSim, I run the environments Blocks (or any other environment such as MountainLandscape), and upon running, then I navigate in terminal and run in a python pipenv (Python 3.9.12) `PythonClient/reinforcement_learning/dqn_drone.py`. The DQN starts off and very shortly thereafter returns an error 

```PS C:\Users\shash\Documents\Thesis\Colosseum\PythonClient\reinforcement_learning> python .\dqn_drone.py
<stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001EAC077CFD0>
Traceback (most recent call last):
  File "C:\Users\shash\Documents\Thesis\Colosseum\PythonClient\reinforcement_learning\dqn_drone.py", line 28, in <module>
    env = VecTransposeImage(env)
  File "C:\Users\shash\.virtualenvs\PythonClient-mo3ke7LZ\lib\site-packages\stable_baselines3\common\vec_env\vec_transpose.py", line 22, in __init__
    assert is_image_space(venv.observation_space) or isinstance(
AssertionError: The observation space must be an image or dictionary observation space```



### Settings
<!-- If not the default, include the settings.json file you are using -->
<!-- If it's too large, you can create a [gist](https://gist.github.com/) and past the link here.  -->

### How can the issue be reproduced?
<!--  Include a detailed step by step process for recreating your issue. -->
<!-- If your issue includes code, create a [gist](https://gist.github.com/) and past the link here. -->

1.
2.

### Include full error message in text form



**What's better than filing an issue? Filing a pull request :).**

**Comment by BetterLL** [comment]
oh I have the same question, how do you solve it?
